---

- hosts: all
  become: true

  pre_tasks:
  - name: install updates(AlmaLinux)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"

  - name: install updates(Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package(AlmaLinux)
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install apache2 and php package(ubuntu)
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package(AlmaLinux)
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install mariadb package(Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
